name: C++ Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Compile tests
      run: g++ -std=c++20 -I. tests.cpp -o tests
    - name: Run tests
      run: ./tests
